name: Compass
on:
  push:
    branches: [main]
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  pipeline:
    uses: HalloftheGods/.github-xophz-compass/.github/workflows/master.yml@main
